# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('xcalib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TREATMENTPLAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=64)),
                ('PatientId', models.CharField(max_length=16)),
                ('LastName', models.CharField(max_length=64)),
                ('FirstName', models.CharField(max_length=64)),
                ('MiddleName', models.CharField(max_length=64)),
                ('DOB', models.DateField()),
                ('TotalDose', models.FloatField()),
                ('Fractions', models.PositiveIntegerField()),
                ('PrescriptionDepth', models.FloatField()),
                ('TargetTissue', models.CharField(choices=[('StriatedMuscle', 'ICRU striated muscle'), ('Skin', 'ICRP skin'), ('SoftTissue', 'ICRU 4-element soft tissue'), ('Lung', 'ICRP lung'), ('CompactBone', 'ICRU compact bone'), ('Water', 'Water'), ('Air', 'Air')], max_length=16)),
                ('CutoutRequired', models.BooleanField(default=False)),
                ('CutoutShape', models.CharField(choices=[('Oval', 'Oval/Circle'), ('Rectangle', 'Rectangle/Square')], max_length=16)),
                ('CutoutLength', models.FloatField()),
                ('CutoutWidth', models.FloatField()),
                ('CutoutThickness', models.FloatField()),
                ('StandOut', models.FloatField()),
                ('FCD', models.FloatField(default=0)),
                ('FSD', models.FloatField(default=0)),
                ('ISF', models.FloatField(default=0)),
                ('Dequiv', models.FloatField(default=0)),
                ('DequivCalib', models.FloatField(default=0)),
                ('DequivSurface', models.FloatField(default=0)),
                ('SpecifyROF', models.BooleanField(default=False)),
                ('ROF', models.FloatField(default=0)),
                ('PDD', models.FloatField(default=100)),
                ('KR_air_CalibCone', models.FloatField(default=0)),
                ('KR_air', models.FloatField(default=0)),
                ('BSF_wat', models.FloatField(default=0)),
                ('BSF_ConeEnd', models.FloatField(default=0)),
                ('MassAbs_WatAir_air', models.FloatField(default=0)),
                ('DR_wat', models.FloatField(default=0)),
                ('C_MedWat', models.FloatField(default=0)),
                ('B_MedWat', models.FloatField(default=0)),
                ('DR_med', models.FloatField(default=0)),
                ('DosePerFrac', models.FloatField(default=0)),
                ('TxTime', models.FloatField(default=0)),
                ('Comment', models.TextField(blank=True, max_length=512)),
                ('SXTCalcVersion', models.CharField(max_length=32)),
                ('DoseCalibDate', models.DateField(null=True)),
                ('ModifiedByUser', models.CharField(max_length=32)),
                ('LastModifiedDateTime', models.DateTimeField(auto_now=True)),
                ('PlanStatus', models.CharField(choices=[('All', 'All'), ('Active', 'Active'), ('Completed', 'Completed'), ('Retired', 'Retired'), ('Cancelled', 'Cancelled')], default='Active', max_length=32)),
                ('StatusChangedBy', models.CharField(blank=True, max_length=32)),
                ('StatusChangeDateTime', models.DateTimeField(auto_now_add=True)),
                ('ApprvStatus', models.CharField(choices=[('All', 'All'), ('NotApproved', "Not Apprv'd"), ('Approved', 'Approved'), ('UnApproved', 'UnApproved')], default='NotApproved', max_length=32)),
                ('ApprovedBy', models.CharField(blank=True, max_length=32)),
                ('ApprvDateTime', models.DateTimeField(auto_now_add=True)),
                ('Cone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.CONE', verbose_name='Applicator')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.DOCTOR', verbose_name='Physician')),
                ('Filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcalib.NOMINALCALIBRATION', verbose_name='Filter')),
            ],
            options={
                'verbose_name_plural': 'Treatment Plans',
            },
        ),
    ]
