# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='ApprvStatus',
            field=models.CharField(choices=[('NotApproved', "Not Apprv'd"), ('Approved', 'Approved'), ('UnApproved', 'UnApproved')], default='NotApproved', max_length=32),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='PlanStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Retired', 'Retired'), ('Cancelled', 'Cancelled')], default='Active', max_length=32),
        ),
    ]
