# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-03 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xcalc', '0002_auto_20190330_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentplan',
            old_name='ROF',
            new_name='ROF_Exposure',
        ),
    ]
