# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHAMBER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChamberName', models.CharField(max_length=64, unique=True, verbose_name='Chamber Name')),
                ('ChamberModel', models.CharField(max_length=64, verbose_name='Chamber Model')),
                ('SerialNumber', models.CharField(max_length=64, unique=True, verbose_name='Serial Number')),
                ('LastModifiedDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CONE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConeCode', models.CharField(max_length=2, unique=True, verbose_name='Applicator Code')),
                ('ConeName', models.CharField(max_length=64, unique=True, verbose_name='Applicator Name')),
                ('Shape', models.CharField(choices=[('Circle', 'Circle'), ('Square', 'Square'), ('Rectangle', 'Rectangle')], default='Circle', max_length=32, verbose_name='Applicator Shape')),
                ('Breadth', models.FloatField(verbose_name='Breadth (cm)')),
                ('Width', models.FloatField(verbose_name='Width (cm)')),
                ('FSD', models.FloatField(verbose_name='Focal Applicator End Dist. (cm)')),
                ('ConeEnd', models.CharField(choices=[('Open', 'Open'), ('PMMA3p2', 'PMMA 3.2 mm')], default='Open', max_length=32, verbose_name='Applicator End')),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Retired', 'Retired')], max_length=32)),
                ('LastModifiedDateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Applicators',
            },
        ),
        migrations.CreateModel(
            name='DOCTOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffId', models.CharField(max_length=16, unique=True, verbose_name='Staff ID')),
                ('LastName', models.CharField(max_length=64, verbose_name='Last Name')),
                ('FirstName', models.CharField(max_length=64, verbose_name='First Name')),
                ('LastModifiedDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ELECTROMETER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElectrometerName', models.CharField(max_length=64, unique=True, verbose_name='Electrometer Name')),
                ('ElectrometerModel', models.CharField(max_length=64, verbose_name='Electrometer Model')),
                ('SerialNumber', models.CharField(max_length=64, unique=True, verbose_name='Serial Number')),
                ('LastModifiedDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FILTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilterCode', models.CharField(max_length=2, unique=True, verbose_name='Filter Code')),
                ('FilterName', models.CharField(max_length=64, unique=True, verbose_name='Filter Name')),
                ('Energy', models.FloatField(verbose_name='Energy (kV)')),
                ('Current', models.FloatField(verbose_name='Current (mA)')),
                ('HVLUnit', models.CharField(choices=[('mm Al', 'mm Al'), ('mm Cu', 'mm Cu')], default='mm Al', max_length=16, verbose_name='HVL Unit')),
                ('NominalHVL', models.FloatField(verbose_name='Nominal HVL')),
                ('HVL', models.FloatField(verbose_name='Measured HVL')),
                ('EndEffect', models.FloatField(default=0.0, verbose_name='End Effect (min or MU)')),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Retired', 'Retired')], max_length=32)),
                ('LastModifiedDateTime', models.DateTimeField(auto_now=True)),
                ('LastModifiedByUser', models.CharField(max_length=32, verbose_name='Last Modified By User')),
            ],
        ),
        migrations.CreateModel(
            name='MACHINE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineCode', models.CharField(max_length=2, unique=True, verbose_name='Machine Code')),
                ('MachineName', models.CharField(max_length=64, unique=True, verbose_name='Machine Name')),
                ('MachineModel', models.CharField(max_length=64, verbose_name='Machine Model')),
                ('SerialNumber', models.CharField(max_length=64, unique=True, verbose_name='Serial Number')),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Retired', 'Retired')], max_length=32)),
                ('OutputControl', models.CharField(choices=[('min', 'Minutes'), ('MU', 'Monitor Units')], max_length=16, verbose_name='Output Control')),
                ('Description', models.TextField(blank=True, max_length=512)),
                ('LastModifiedDateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'X-Ray Machines',
            },
        ),
        migrations.AddField(
            model_name='filter',
            name='Machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.MACHINE'),
        ),
        migrations.AddField(
            model_name='cone',
            name='Machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.MACHINE'),
        ),
    ]
