# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Retired', 'Retired')], default='Active', max_length=32),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=32),
        ),
        migrations.AddField(
            model_name='electrometer',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Retired', 'Retired')], default='Active', max_length=32),
        ),
    ]
