# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20190330_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cone',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Retired', 'Retired')], default='Active', max_length=32),
        ),
        migrations.AlterField(
            model_name='filter',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Retired', 'Retired')], default='Active', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Retired', 'Retired')], default='Active', max_length=32),
        ),
    ]
