# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20190330_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='MiddleName',
            field=models.CharField(default='', max_length=64, verbose_name='Middle Name'),
            preserve_default=False,
        ),
    ]
