# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_doctor_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=64, verbose_name='Middle Name'),
        ),
    ]
