# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcalib', '0002_auto_20181205_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementset',
            name='MSetName',
            field=models.CharField(max_length=32, verbose_name='Meas Set Name'),
        ),
    ]
