# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcalib', '0003_auto_20181205_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementset',
            name='Note',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
