# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcalib', '0004_measurementset_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominalcalibration',
            options={'verbose_name': 'Nominal Calibration'},
        ),
        migrations.RemoveField(
            model_name='measurementset',
            name='Note',
        ),
        migrations.AlterField(
            model_name='calibration',
            name='DR_Air',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Air Kerma Rate in Air'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='DR_Water',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Dose Rate at Water Surface'),
        ),
        migrations.AlterField(
            model_name='nominalcalibration',
            name='DR_Air',
            field=models.FloatField(default=0.0, verbose_name='Air Kerma Rate in Air (cGy/MU or cGy/min)'),
        ),
        migrations.AlterField(
            model_name='nominalcalibration',
            name='DR_Water',
            field=models.FloatField(default=0.0, verbose_name='Dose Rate at Water Surface (cGy/MU or cGy/min)'),
        ),
    ]
