# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xcalib', '0006_auto_20190107_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominalcalibration',
            name='ActualCalib',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='xcalib.CALIBRATION'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Has_Pion_Ppol',
            field=models.BooleanField(default=False, verbose_name='User Specify Pion Ppol'),
        ),
    ]
