version: '3'

networks:
  sxt_network:
    driver: bridge

services:
  superdocs:
    build: .
    volumes:
      - sxt_vol:/var/www/SuperDoCS/sxtweb
      - static_vol:/var/www/SuperDoCS/static
      - media_vol:/var/www/SuperDoCS/media
      - usercodes_vol:/var/www/SuperDoCS/xcalc/UserCodes
      - nginxconf_vol:/var/www/SuperDoCS/config/nginx_conf.d
#    ports:
#      - "8000:8000"
    networks:
      - sxt_network

  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - static_vol:/var/www/SuperDoCS/static
      - media_vol:/var/www/SuperDoCS/media
      - nginxconf_vol:/etc/nginx/conf.d
    networks:
      - sxt_network
    depends_on:
      - superdocs

volumes:
  static_vol:
  media_vol:
  sxt_vol:
  usercodes_vol:
  nginxconf_vol:

